version: '3.9'

services: 
  dbclases:
    image: postgres:15-alpine
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=ejemplo1
      - POSTGRES_USER=quinto
      - POSTGRES_PASSWORS=123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - pg_dbclase:/var/lib/postgresql/data/pgdata
    networks:
      - net_dbclase
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL: bm@wasa.edu.ec
      - PGADMIN_DEFAULT_PASSWORK: 1234
    volumes: 
      - pg_pgadmin:/var/lib/pgadmin
    networks:
      - 



volumes:
  pg_dbclase:
    external: true
networks:
  net_dbclase:
    external: true
